import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth,onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore,doc,getDoc,collection,addDoc,query,orderBy,onSnapshot,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { getStorage,ref,uploadBytes,getDownloadURL } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
const configured=!Object.values(firebaseConfig).some(v=>String(v).includes("YOUR_"));
const out=document.getElementById("loggedOut"),layout=document.getElementById("feedLayout");
if(!configured){out.querySelector("p").textContent="Firebase must be configured before the community can be used."}
else{
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const resize=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const sc=Math.min(1,1200/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=i.width*sc;c.height=i.height*sc;c.getContext("2d").drawImage(i,0,0,c.width,c.height);c.toBlob(res,"image/jpeg",.82)};i.src=r.result};r.onerror=rej;r.readAsDataURL(f)});
onAuthStateChanged(auth,async u=>{if(!u){out.classList.remove("hidden");layout.classList.add("hidden");return}const s=await getDoc(doc(db,"users",u.uid));if(!s.exists()){location.href="citizen-login.html";return}out.classList.add("hidden");layout.classList.remove("hidden");const user=s.data();document.getElementById("sidebarProfile").innerHTML=`<div class="avatar large">${user.photoURL?`<img src="${esc(user.photoURL)}">`:"👤"}</div><h3>${esc(user.name)}</h3><p>Asko Citizen</p>`;document.getElementById("createAvatar").innerHTML=user.photoURL?`<img src="${esc(user.photoURL)}">`:"👤";loadFeed()});
async function loadFeed(){onSnapshot(query(collection(db,"posts"),orderBy("createdAt","desc")),snap=>{const box=document.getElementById("feedMessages");box.innerHTML="";if(snap.empty){box.innerHTML='<div class="empty-feed card">No posts yet. Be the first to post.</div>';return}snap.forEach(x=>{const p=x.data(),d=p.createdAt?.toDate?.().toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})||"Just now",a=document.createElement("article");a.className="post card";a.innerHTML=`<div class="post-head"><div class="avatar">${p.photoURL?`<img src="${esc(p.photoURL)}">`:"👤"}</div><div><b>${esc(p.name)}</b><small>${d}</small></div></div>${p.text?`<div class="post-text">${esc(p.text)}</div>`:""}${p.imageURL?`<img class="post-image" src="${esc(p.imageURL)}">`:""}<div class="post-actions"><button>👍 Like</button><button>💬 Comment</button><button>↗ Share</button></div>`;box.appendChild(a)})})}
document.getElementById("postForm").onsubmit=async e=>{e.preventDefault();const u=auth.currentUser,text=document.getElementById("postText").value.trim(),f=document.getElementById("postImage").files[0];if(!u||(!text&&!f))return;const user=(await getDoc(doc(db,"users",u.uid))).data();let imageURL="";if(f){const b=await resize(f),r=ref(storage,`posts/${u.uid}/${Date.now()}.jpg`);await uploadBytes(r,b,{contentType:"image/jpeg"});imageURL=await getDownloadURL(r)}await addDoc(collection(db,"posts"),{uid:u.uid,name:user.name,photoURL:user.photoURL||"",text,imageURL,createdAt:serverTimestamp()});document.getElementById("postText").value="";document.getElementById("postImage").value=""};
}